# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""
GeomTools module, see official documentation at
https://www.opencascade.com/doc/occt-7.6.0/refman/html/package_geomtools.html
"""

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _GeomTools
else:
    import _GeomTools

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _GeomTools.delete_SwigPyIterator

    def value(self) -> "PyObject *":
        return _GeomTools.SwigPyIterator_value(self)

    def incr(self, n: "size_t"=1) -> "swig::SwigPyIterator *":
        return _GeomTools.SwigPyIterator_incr(self, n)

    def decr(self, n: "size_t"=1) -> "swig::SwigPyIterator *":
        return _GeomTools.SwigPyIterator_decr(self, n)

    def distance(self, x: "SwigPyIterator") -> "ptrdiff_t":
        return _GeomTools.SwigPyIterator_distance(self, x)

    def equal(self, x: "SwigPyIterator") -> "bool":
        return _GeomTools.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _GeomTools.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _GeomTools.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _GeomTools.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _GeomTools.SwigPyIterator_previous(self)

    def advance(self, n: "ptrdiff_t") -> "swig::SwigPyIterator *":
        return _GeomTools.SwigPyIterator_advance(self, n)

    def __eq__(self, x: "SwigPyIterator") -> "bool":
        return _GeomTools.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: "SwigPyIterator") -> "bool":
        return _GeomTools.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator &":
        return _GeomTools.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator &":
        return _GeomTools.SwigPyIterator___isub__(self, n)

    def __add__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator *":
        return _GeomTools.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _GeomTools.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _GeomTools:
_GeomTools.SwigPyIterator_swigregister(SwigPyIterator)


def _dumps_object(klass):
    """ Overwrite default string output for any wrapped object.
    By default, __repr__ method returns something like:
    <OCC.Core.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x02BB0758> >
    This is too much verbose.
    We prefer :
    <class 'gp_Pnt'>
    or
    <class 'TopoDS_Shape'>
    """
    klass_name = str(klass.__class__).split(".")[3].split("'")[0]
    repr_string = "<class '" + klass_name + "'"
# for TopoDS_Shape, we also look for the base type
    if klass_name == "TopoDS_Shape":
        if klass.IsNull():
            repr_string += ": Null>"
            return repr_string
        st = klass.ShapeType()
        types = {OCC.Core.TopAbs.TopAbs_VERTEX: "Vertex",
                 OCC.Core.TopAbs.TopAbs_SOLID: "Solid",
                 OCC.Core.TopAbs.TopAbs_EDGE: "Edge",
                 OCC.Core.TopAbs.TopAbs_FACE: "Face",
                 OCC.Core.TopAbs.TopAbs_SHELL: "Shell",
                 OCC.Core.TopAbs.TopAbs_WIRE: "Wire",
                 OCC.Core.TopAbs.TopAbs_COMPOUND: "Compound",
                 OCC.Core.TopAbs.TopAbs_COMPSOLID: "Compsolid"}
        repr_string += "; Type:%s" % types[st]        
    elif hasattr(klass, "IsNull"):
        if klass.IsNull():
            repr_string += "; Null"
    repr_string += ">"
    return repr_string


def process_exception(error: "Standard_Failure", method_name: "std::string", class_name: "std::string") -> "void":
    return _GeomTools.process_exception(error, method_name, class_name)

from six import with_metaclass
import warnings
from OCC.Wrapper.wrapper_utils import Proxy, deprecated

import OCC.Core.Standard
import OCC.Core.NCollection
import OCC.Core.Geom
import OCC.Core.gp
import OCC.Core.TColStd
import OCC.Core.TCollection
import OCC.Core.GeomAbs
import OCC.Core.TColgp
import OCC.Core.Geom2d

from enum import IntEnum
from OCC.Core.Exception import *




def Handle_GeomTools_UndefinedTypeHandler_Create() -> "opencascade::handle< GeomTools_UndefinedTypeHandler >":
    return _GeomTools.Handle_GeomTools_UndefinedTypeHandler_Create()

def Handle_GeomTools_UndefinedTypeHandler_DownCast(t: "opencascade::handle< Standard_Transient > const &") -> "opencascade::handle< GeomTools_UndefinedTypeHandler >":
    return _GeomTools.Handle_GeomTools_UndefinedTypeHandler_DownCast(t)

def Handle_GeomTools_UndefinedTypeHandler_IsNull(t: "opencascade::handle< GeomTools_UndefinedTypeHandler > const &") -> "bool":
    return _GeomTools.Handle_GeomTools_UndefinedTypeHandler_IsNull(t)
class geomtools(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def GetUndefinedTypeHandler(*args) -> "opencascade::handle< GeomTools_UndefinedTypeHandler >":
        r"""
        No available documentation.

        Returns
        -------
        opencascade::handle<GeomTools_UndefinedTypeHandler>

        """
        return _GeomTools.geomtools_GetUndefinedTypeHandler(*args)

    @staticmethod
    def SetUndefinedTypeHandler(*args) -> "void":
        r"""
        No available documentation.

        Parameters
        ----------
        aHandler: GeomTools_UndefinedTypeHandler

        Returns
        -------
        None

        """
        return _GeomTools.geomtools_SetUndefinedTypeHandler(*args)

    __repr__ = _dumps_object


    def __init__(self):
        _GeomTools.geomtools_swiginit(self, _GeomTools.new_geomtools())
    __swig_destroy__ = _GeomTools.delete_geomtools

# Register geomtools in _GeomTools:
_GeomTools.geomtools_swigregister(geomtools)

def geomtools_GetUndefinedTypeHandler(*args) -> "opencascade::handle< GeomTools_UndefinedTypeHandler >":
    r"""
    No available documentation.

    Returns
    -------
    opencascade::handle<GeomTools_UndefinedTypeHandler>

    """
    return _GeomTools.geomtools_GetUndefinedTypeHandler(*args)

def geomtools_SetUndefinedTypeHandler(*args) -> "void":
    r"""
    No available documentation.

    Parameters
    ----------
    aHandler: GeomTools_UndefinedTypeHandler

    Returns
    -------
    None

    """
    return _GeomTools.geomtools_SetUndefinedTypeHandler(*args)

class GeomTools_Curve2dSet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Returns an empty set of curves.

        Returns
        -------
        None

        """
        _GeomTools.GeomTools_Curve2dSet_swiginit(self, _GeomTools.new_GeomTools_Curve2dSet(*args))

    def Add(self, *args) -> "Standard_Integer":
        r"""
        Incorporate a new curve in the set and returns its index.

        Parameters
        ----------
        C: Geom2d_Curve

        Returns
        -------
        int

        """
        return _GeomTools.GeomTools_Curve2dSet_Add(self, *args)

    def Clear(self, *args) -> "void":
        r"""
        Clears the content of the set.

        Returns
        -------
        None

        """
        return _GeomTools.GeomTools_Curve2dSet_Clear(self, *args)

    def Curve2d(self, *args) -> "opencascade::handle< Geom2d_Curve >":
        r"""
        Returns the curve of index <i>.

        Parameters
        ----------
        I: int

        Returns
        -------
        opencascade::handle<Geom2d_Curve>

        """
        return _GeomTools.GeomTools_Curve2dSet_Curve2d(self, *args)

    def DumpToString(self) -> "std::string":
        r"""DumpToString(GeomTools_Curve2dSet self) -> std::string"""
        return _GeomTools.GeomTools_Curve2dSet_DumpToString(self)

    def Index(self, *args) -> "Standard_Integer":
        r"""
        Returns the index of <l>.

        Parameters
        ----------
        C: Geom2d_Curve

        Returns
        -------
        int

        """
        return _GeomTools.GeomTools_Curve2dSet_Index(self, *args)

    def ReadFromString(self, src: "std::string") -> "void":
        r"""ReadFromString(GeomTools_Curve2dSet self, std::string src)"""
        return _GeomTools.GeomTools_Curve2dSet_ReadFromString(self, src)

    def ReadCurve2dFromString(self, src: "std::string") -> "void":
        r"""ReadCurve2dFromString(GeomTools_Curve2dSet self, std::string src)"""
        return _GeomTools.GeomTools_Curve2dSet_ReadCurve2dFromString(self, src)

    def WriteToString(self) -> "std::string":
        r"""WriteToString(GeomTools_Curve2dSet self) -> std::string"""
        return _GeomTools.GeomTools_Curve2dSet_WriteToString(self)

    __repr__ = _dumps_object

    __swig_destroy__ = _GeomTools.delete_GeomTools_Curve2dSet

# Register GeomTools_Curve2dSet in _GeomTools:
_GeomTools.GeomTools_Curve2dSet_swigregister(GeomTools_Curve2dSet)

class GeomTools_CurveSet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Returns an empty set of curves.

        Returns
        -------
        None

        """
        _GeomTools.GeomTools_CurveSet_swiginit(self, _GeomTools.new_GeomTools_CurveSet(*args))

    def Add(self, *args) -> "Standard_Integer":
        r"""
        Incorporate a new curve in the set and returns its index.

        Parameters
        ----------
        C: Geom_Curve

        Returns
        -------
        int

        """
        return _GeomTools.GeomTools_CurveSet_Add(self, *args)

    def Clear(self, *args) -> "void":
        r"""
        Clears the content of the set.

        Returns
        -------
        None

        """
        return _GeomTools.GeomTools_CurveSet_Clear(self, *args)

    def Curve(self, *args) -> "opencascade::handle< Geom_Curve >":
        r"""
        Returns the curve of index <i>.

        Parameters
        ----------
        I: int

        Returns
        -------
        opencascade::handle<Geom_Curve>

        """
        return _GeomTools.GeomTools_CurveSet_Curve(self, *args)

    def DumpToString(self) -> "std::string":
        r"""DumpToString(GeomTools_CurveSet self) -> std::string"""
        return _GeomTools.GeomTools_CurveSet_DumpToString(self)

    def Index(self, *args) -> "Standard_Integer":
        r"""
        Returns the index of <l>.

        Parameters
        ----------
        C: Geom_Curve

        Returns
        -------
        int

        """
        return _GeomTools.GeomTools_CurveSet_Index(self, *args)

    def ReadFromString(self, src: "std::string") -> "void":
        r"""ReadFromString(GeomTools_CurveSet self, std::string src)"""
        return _GeomTools.GeomTools_CurveSet_ReadFromString(self, src)

    def ReadCurveFromString(self, src: "std::string") -> "void":
        r"""ReadCurveFromString(GeomTools_CurveSet self, std::string src)"""
        return _GeomTools.GeomTools_CurveSet_ReadCurveFromString(self, src)

    def WriteToString(self) -> "std::string":
        r"""WriteToString(GeomTools_CurveSet self) -> std::string"""
        return _GeomTools.GeomTools_CurveSet_WriteToString(self)

    __repr__ = _dumps_object

    __swig_destroy__ = _GeomTools.delete_GeomTools_CurveSet

# Register GeomTools_CurveSet in _GeomTools:
_GeomTools.GeomTools_CurveSet_swigregister(GeomTools_CurveSet)

class GeomTools_SurfaceSet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Returns an empty set of surfaces.

        Returns
        -------
        None

        """
        _GeomTools.GeomTools_SurfaceSet_swiginit(self, _GeomTools.new_GeomTools_SurfaceSet(*args))

    def Add(self, *args) -> "Standard_Integer":
        r"""
        Incorporate a new surface in the set and returns its index.

        Parameters
        ----------
        S: Geom_Surface

        Returns
        -------
        int

        """
        return _GeomTools.GeomTools_SurfaceSet_Add(self, *args)

    def Clear(self, *args) -> "void":
        r"""
        Clears the content of the set.

        Returns
        -------
        None

        """
        return _GeomTools.GeomTools_SurfaceSet_Clear(self, *args)

    def DumpToString(self) -> "std::string":
        r"""DumpToString(GeomTools_SurfaceSet self) -> std::string"""
        return _GeomTools.GeomTools_SurfaceSet_DumpToString(self)

    def Index(self, *args) -> "Standard_Integer":
        r"""
        Returns the index of <l>.

        Parameters
        ----------
        S: Geom_Surface

        Returns
        -------
        int

        """
        return _GeomTools.GeomTools_SurfaceSet_Index(self, *args)

    def ReadFromString(self, src: "std::string") -> "void":
        r"""ReadFromString(GeomTools_SurfaceSet self, std::string src)"""
        return _GeomTools.GeomTools_SurfaceSet_ReadFromString(self, src)

    def ReadSurfaceFromString(self, src: "std::string") -> "void":
        r"""ReadSurfaceFromString(GeomTools_SurfaceSet self, std::string src)"""
        return _GeomTools.GeomTools_SurfaceSet_ReadSurfaceFromString(self, src)

    def Surface(self, *args) -> "opencascade::handle< Geom_Surface >":
        r"""
        Returns the surface of index <i>.

        Parameters
        ----------
        I: int

        Returns
        -------
        opencascade::handle<Geom_Surface>

        """
        return _GeomTools.GeomTools_SurfaceSet_Surface(self, *args)

    def WriteToString(self) -> "std::string":
        r"""WriteToString(GeomTools_SurfaceSet self) -> std::string"""
        return _GeomTools.GeomTools_SurfaceSet_WriteToString(self)

    __repr__ = _dumps_object

    __swig_destroy__ = _GeomTools.delete_GeomTools_SurfaceSet

# Register GeomTools_SurfaceSet in _GeomTools:
_GeomTools.GeomTools_SurfaceSet_swigregister(GeomTools_SurfaceSet)

class GeomTools_UndefinedTypeHandler(OCC.Core.Standard.Standard_Transient):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        No available documentation.

        Returns
        -------
        None

        """
        _GeomTools.GeomTools_UndefinedTypeHandler_swiginit(self, _GeomTools.new_GeomTools_UndefinedTypeHandler(*args))


    @staticmethod
    def DownCast(t):
      return Handle_GeomTools_UndefinedTypeHandler_DownCast(t)


    __repr__ = _dumps_object

    __swig_destroy__ = _GeomTools.delete_GeomTools_UndefinedTypeHandler

# Register GeomTools_UndefinedTypeHandler in _GeomTools:
_GeomTools.GeomTools_UndefinedTypeHandler_swigregister(GeomTools_UndefinedTypeHandler)





