#!/usr/bin/env python3
"""
Fibonacci Lattice Generator for Full Angle Drop Simulation

피보나치 격자를 이용한 전각도 낙하 시뮬레이션 케이스 생성기

Usage:
    python fibonacci_lattice_generator.py --angle 10
    python fibonacci_lattice_generator.py --cases 413
    python fibonacci_lattice_generator.py --angle 5 --output my_drop.txt

Author: koo.park (koo.park@samsung.com)
"""

import math
import argparse
import os


def fibonacci_sphere(n):
    """
    피보나치 격자로 N개 점을 구면에 균등 분포

    Parameters:
        n: 생성할 점의 개수

    Returns:
        List of (x, y, z) unit vectors
    """
    points = []
    phi = math.pi * (3.0 - math.sqrt(5.0))  # 황금각 ≈ 137.508°

    for i in range(n):
        # y: 1 ~ -1 균등 분포 (위도 방향)
        y = 1 - (i / float(n - 1)) * 2 if n > 1 else 0

        # xz 평면에서의 반지름
        radius = math.sqrt(1 - y * y)

        # 황금각 누적 (경도 방향)
        theta = phi * i

        # 직교 좌표
        x = math.cos(theta) * radius
        z = math.sin(theta) * radius

        points.append((x, y, z))

    return points


def vector_to_euler(x, y, z):
    """
    방향 벡터를 오일러 각도 (Roll, Pitch, Yaw)로 변환

    좌표계:
        - 원점: 스마트폰 하단 중심
        - +Z: 디스플레이 방향 (전면)
        - +X: 오른쪽
        - +Y: 위쪽

    Returns:
        (roll, pitch, yaw) in degrees
    """
    r = math.sqrt(x*x + y*y + z*z)

    if r == 0:
        return (0, 0, 0)

    # 구면 좌표 계산
    lat = math.asin(max(-1, min(1, y / r)))  # 위도
    lon = math.atan2(z, x)  # 경도

    # 오일러 각도 변환
    roll = math.degrees(lat) - 90
    pitch = -math.degrees(lon)
    yaw = 0

    return (round(roll, 2), round(pitch, 2), round(yaw, 2))


def fibonacci_sphere_euler(n):
    """
    피보나치 격자 N개 점을 오일러 각도로 반환

    Returns:
        List of (name, roll, pitch, yaw)
    """
    points = fibonacci_sphere(n)
    results = []

    for i, (x, y, z) in enumerate(points):
        roll, pitch, yaw = vector_to_euler(x, y, z)
        results.append((f"P{i+1:04d}", roll, pitch, yaw))

    return results


def angle_to_cases(angle_deg):
    """
    목표 각도 간격 → 필요 케이스 수

    공식: N ≈ 4π / (θ × π/180)² = 41253 / θ²
    """
    angle_rad = angle_deg * math.pi / 180
    return round(4 * math.pi / (angle_rad ** 2))


def cases_to_angle(n):
    """
    케이스 수 → 평균 각도 간격

    공식: θ ≈ √(4π/N) × (180/π) ≈ 233.6 / √N
    """
    return math.sqrt(4 * math.pi / n) * (180 / math.pi)


def generate_drop_file(cases, output_path, height=1500, info_name=None, description=None):
    """
    DROP_ATTITUDE 파일 생성

    Parameters:
        cases: List of (name, roll, pitch, yaw)
        output_path: 출력 파일 경로
        height: 낙하 높이 (mm)
        info_name: 정보 이름
        description: 설명
    """
    n = len(cases)
    angle = cases_to_angle(n)

    if info_name is None:
        info_name = f"FullAngle_Fibonacci_{n}cases"

    if description is None:
        description = f"Full Angle Drop - Fibonacci Lattice {n} cases ~{angle:.1f}deg spacing"

    # 데이터 추출
    names = [c[0] for c in cases]
    rolls = [c[1] for c in cases]
    pitches = [c[2] for c in cases]
    yaws = [c[3] for c in cases]

    # 파일 내용 생성
    content = f"""*Inputfile
MinimumModel.k
*RunDirectoryMode,True,Data/Results,Data/Metadata
*Info,Smartphone,{info_name}
*Description,{description}
*Creator,koo.park,koo.park@samsung.com,CAE,HE
*Mode
DROP_ATTITUDE,1
**DropAttitude,1
$ ============================================================================
$ {description}
$ Total cases: {n}
$ Average angular spacing: {angle:.2f} degrees
$ Generated by fibonacci_lattice_generator.py
$ ============================================================================
$ {','.join(names)}
EulerRolling,{','.join(str(r) for r in rolls)}
EulerPitching,{','.join(str(p) for p in pitches)}
EulerYawing,{','.join(str(y) for y in yaws)}
Height,{','.join(str(height) for _ in cases)}
InitialVelocityX,{','.join('0' for _ in cases)}
InitialVelocityY,{','.join('0' for _ in cases)}
InitialVelocityZ,{','.join('0' for _ in cases)}
InitialAngularVelocityX,{','.join('0' for _ in cases)}
InitialAngularVelocityY,{','.join('0' for _ in cases)}
InitialAngularVelocityZ,{','.join('0' for _ in cases)}
OffsetDistance,0.1
Density,7850
YoungsModulus,200000000000
PoissonRatio,0.3
tFinal,0.005
dt,0.000001
DropSurface,Plane,300,300,20,30,30,2
**EndDropAttitude
*End
"""

    with open(output_path, 'w') as f:
        f.write(content)

    return output_path


def print_reference_table():
    """참조표 출력"""
    print("\n피보나치 격자 참조표")
    print("=" * 50)
    print(f"{'각도 간격':>12} | {'케이스 수':>10} | {'용도':>15}")
    print("-" * 50)

    references = [
        (40, "빠른 검증"),
        (20, "표준 분석"),
        (10, "상세 분석"),
        (6, "정밀 분석"),
        (5, "정밀 분석"),
        (4, "고정밀 분석"),
        (2, "초고정밀"),
        (1, "연구용"),
    ]

    for angle, purpose in references:
        n = angle_to_cases(angle)
        actual_angle = cases_to_angle(n)
        print(f"{angle:>10}° | {n:>10} | {purpose:>15}")

    print("=" * 50)


def main():
    parser = argparse.ArgumentParser(
        description='피보나치 격자 전각도 낙하 케이스 생성기',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --angle 10                    # 10도 간격 (413개)
  %(prog)s --cases 1000                  # 1000개 케이스
  %(prog)s --angle 5 --output drop.txt   # 5도 간격, 파일 지정
  %(prog)s --angle 20 --height 1800      # 20도 간격, 1.8m 높이
  %(prog)s --table                       # 참조표 출력
        """
    )

    group = parser.add_mutually_exclusive_group()
    group.add_argument('--angle', type=float, help='목표 각도 간격 (도)')
    group.add_argument('--cases', type=int, help='케이스 수')
    group.add_argument('--table', action='store_true', help='참조표 출력')

    parser.add_argument('--output', '-o', type=str, help='출력 파일 경로')
    parser.add_argument('--height', type=int, default=1500, help='낙하 높이 (mm, 기본값: 1500)')
    parser.add_argument('--info', type=str, help='정보 이름')
    parser.add_argument('--desc', type=str, help='설명')

    args = parser.parse_args()

    # 참조표 출력
    if args.table:
        print_reference_table()
        return

    # 케이스 수 결정
    if args.angle:
        n_cases = angle_to_cases(args.angle)
        print(f"목표 각도: {args.angle}° → {n_cases}개 케이스")
    elif args.cases:
        n_cases = args.cases
        print(f"케이스 수: {n_cases}개 → 평균 각도: {cases_to_angle(n_cases):.2f}°")
    else:
        parser.print_help()
        print("\n--angle 또는 --cases 중 하나를 지정하세요.")
        return

    # 케이스 생성
    print(f"피보나치 격자 생성 중...")
    cases = fibonacci_sphere_euler(n_cases)

    # 출력 파일 경로
    if args.output:
        output_path = args.output
    else:
        angle = round(cases_to_angle(n_cases))
        output_path = f"fibonacci_{angle:02d}deg_{n_cases}cases.txt"

    # 파일 생성
    generate_drop_file(
        cases,
        output_path,
        height=args.height,
        info_name=args.info,
        description=args.desc
    )

    print(f"생성 완료: {output_path}")
    print(f"  - 케이스 수: {n_cases}")
    print(f"  - 평균 각도 간격: {cases_to_angle(n_cases):.2f}°")
    print(f"  - 낙하 높이: {args.height}mm")


if __name__ == "__main__":
    main()
